
name: Fly Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check if the app name is registered in fly.io
        run: |
            if [ ! -f registered_app_domain.txt ]; then
              echo -e "\033[0;33mWarning: App name is not registered.\033[0m"
              echo -e "\033[0;33mGithub Actions may fail if you push without registering.\033[0m"
              echo -e "\033[0;33mRegister your app name by running the script 'scripts/register_to_fly_io.sh'.\033[0m"
              exit 1
            fi

      - name: Deploy to Fly
        run: |
            fly deploy --remote-only --config fly.toml --yes
            fly scale count 1 --config fly.toml --yes
            fly secrets set OPENAI_API_KEY=$OPENAI_API_KEY
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
